### ISSUE TITLE
Enable rearranging the buttons of the ConfirmDialog

### ISSUE THREAD

**Issue by pbodnar** [samie/Vaadin-ConfirmDialog#29]
There should be an easy way of how to rearrange the buttons (yes/no/cancel) of the ConfirmDialog. BTW I don't know the exact statistics, but I do think that **the most usual ordering**, at least on web, is really yes/no/cancel, not the actual cancel/no/yes variant.

This feature is also questioned on SO: http://stackoverflow.com/questions/36326212/how-to-rearrange-buttons-on-vaadin-confirmdialog. The only suggested solution of overriding DefaultConfirmDialogFactory is working of course, but imagine that every client using this add-on needs to implement this over and over again, forced to copy-paste most of the original class (and merge it with newer versions thereafter). What is this good for ...? ;)

Solution proposal: It should be probably enough just to introduce a flag called "buttonOrder" (or similar) and put the created buttons into the actual "buttons" container in the selected order from inside the `DefaultConfirmDialogFactory.create()` method.

**Comment by Thibstars** [comment]
I'd like to add to this issue, that it is probably also a good idea to support optional buttons. For example, if you pass `null` to the `ConfirmDialog.show();` method on a parameter like `cancelCaption`, the button should simply not be included in the dialog.

**Comment by samie** [comment]
Rearranging support is added in version 3.2.0 by https://github.com/samie/Vaadin-ConfirmDialog/pull/38 Overriding orderButtons method in Factory is needed for that.
