### ISSUE TITLE
ContentMode in Vaadin 8 Beta 2

### ISSUE THREAD

**Issue by WLash** [samie/Vaadin-ConfirmDialog#30]
Hi,
the ConfirmDialog version 3.1.0 has problems with finding ContentMode because its destination was moved in the new Beta2.

Thank You

**Comment by ossd** [comment]
Same error in 8.0.0 final. Please change import of ContentMode.

**Comment by samie** [comment]
Fixed in 3.x series by https://github.com/samie/Vaadin-ConfirmDialog/pull/31
