### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by dobrivoje** [samie/Vaadin-ConfirmDialog#32]
I-m using vaadin 7.7.6 and recently, I also experienced error : 
"java.lang.NoSuchMethodError: org.vaadin.dialogs.ConfirmDialog.addCloseListener(Lcom/vaadin/ui/Window$CloseListener;)Lcom/vaadin/shared/Registration"

**Comment by Nuraddin** [comment]
I had same error with version 3.1.1, but error is fixed when changing to version 2.1.3

**Comment by oliverkiderle** [comment]
Having the same issue on Vaadin 7.7.7

**Comment by samie** [comment]
There are differences in Vaadin 8 and Vaadin 7 versions. Please use 2.x for Vaadin 7 and 3.x for Vaadin 8.
